[workspace]
members = [
    "del-msh-pyo3",
    "del-msh-core",
    "del-msh-nalgebra",
    "del-cudarc-bvh",
]
exclude = [
    "kernel-bvh"
]
resolver = "2"

[workspace.package]
version = "0.1.36"
edition = "2021"
authors = ["Nobuyuki Umetani <n.umetani@gmail.com>"]
license = "MIT"
repository = "https://github.com/nobuyuki83/del-msh/"
description = "mesh utility library for computer graphics research and prototyping"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies.cudarc]
version = "*"
features = [
    "std", "cublas", "cublaslt", "curand", "driver", "nvrtc",
    "f16", "cuda-version-from-build-system", "dynamic-linking"]
default-features=false

[workspace.dependencies]
anyhow = "1.0.86"
rand = "0.8.5"
rand_chacha = "0.3.1"
ordered-float = "4.2.1"
num-traits = "0.2.19"
nalgebra = "0.33.0"
arrayref = "0.3.7"
itertools = "0.13.0"
slice-of-array = "0.3.2"
bindgen_cuda = "0.1.5"

# internal
del-msh-nalgebra = { path="del-msh-nalgebra"}
del-msh-core = {path="del-msh-core"}
del-cudarc-bvh = {path="del-cudarc-bvh"}
kernel-bvh = {path="kernel-bvh"}

# for development
del-geo-core = { path="../del-geo/del-geo-core"}
del-geo-nalgebra = { path="../del-geo/del-geo-nalgebra"}
del-cudarc-util = { path="../del-cudarc/del-cudarc-util"}
del-canvas-image = {path="../del-canvas/del-canvas-image"}
# for GitHub push
# del-geo-core = { git = "https://github.com/nobuyuki83/del-geo.git"}
# del-geo-nalgebra = { git = "https://github.com/nobuyuki83/del-geo.git"}
# for deploy
# del-geo-core = "0.1.32"
# del-geo-nalgebra = "0.1.32"

